apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: techtrendsLabel
  name: techtrends
  namespace: {{ .Values.namespace.name }}
## Define the desired configuration for the Deployment resource.
spec:
  ## Set the number of replicas.
  replicas:  {{ .Values.replicaCount }}
  ## Identify the pods managed by this Deployment using the following selectors.
  selector:
    matchLabels:
      app: techtrendsLabel
  ## Set the configuration for the pods.
  template:
    metadata:
      labels:
        app: techtrendsLabel
      ## Define the desired state of the pod configuration.
    spec:
      containers:
      ## Set the image to be executed inside the container and image pull policy
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        livenessProbe:
           httpGet:
             path: {{ .Values.livenessProbe.path }}
             port: {{ .Values.livenessProbe.port }}
        readinessProbe:
           httpGet:
             path: {{ .Values.readinessProbe.path }}
             port: {{ .Values.readinessProbe.port }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}