## Set the API endpoint used to create the Service resource.
apiVersion: v1
## Define the type of the resource.
kind: Service
## Set the parameters that make the object identifiable, such as its name, namespace, and labels.
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
## Define the desired configuration for the Service resource.
spec:
  ## Define the ports that the service should serve on. 
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.port }} 
  ## Identify the pods managed by this Service using the following selectors.
  selector:
    app: techtrendsLabel
  ## Define the Service type, here set to ClusterIP.
  type: {{ .Values.service.type }}