apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
## Define the desired configuration for the Deployment resource.
spec:
  ## Set the number of replicas.
  replicas: {{ .Values.replicaCount }} 
  ## Identify the pods managed by this Deployment using the following selectors.
  selector:
    matchLabels:
      app: techtrendsLabel
  ## Set the configuration for the pods.
  template:
    ## Define the identifiable metadata for the pods.
    metadata:
      labels:
        app: techtrendsLabel
    ## Define the desired state of the pod configuration.
    spec:
      containers:
        ## Set the image to be executed inside the container and image pull policy
      - image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends
        ## Expose the port the container is listening on.
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        ## Define the rules for the liveness probes.
        livenessProbe:
           httpGet:
             path: {{ .Values.livenessProbe.path }}
             port: {{ .Values.livenessProbe.port }}
        ## Define the rules for the readiness probes.
        readinessProbe:
           httpGet:
             path: {{ .Values.readinessProbe.path }}
             port: {{ .Values.readinessProbe.port }}
        ## Set the resource requests and limits for an application.
        resources:
        ## The resource requests guarantees that the desired amount 
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        ## The resource limits ensure that the application is not consuming 
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}