namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP

image:
  repository: amrelboridy/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

containerPorts:
  http: 3111
  https: 3111

livenessProbe:
  enabled: true
  httpGet:
    path: /healthz

readinessProbe:
  enabled: true
  httpGet:
    path: /healthz
